### ISSUE TITLE
(poolparty), :'( are not emotes anymore 

### ISSUE THREAD

**Issue by cinemassacres** [FrankerFaceZ/Add-Ons#1]
Describe the bug
in the bttv addon you have this line, the Enable to show arbitrary emoticons (like D:, :tf:, (poolparty), :'( and similar). (poolparty), :'( are gone and are not emotes anymore
To Reproduce

Go to 'addons'
Click on 'bttv'
Scroll down to rbitrary Emotes
Enable to show arbitrary emoticons (like D:, :tf:, (poolparty), :'( and similar).'
See error
(poolparty), :'( and similar) are not emotes anymore
Expected behavior
that line to be edited to say the Enable to show arbitrary emoticons D: :tf:
Screenshots
https://i.imgur.com/ehrxsaR.png https://imgur.com/ynD9GDN
Environment (please complete the following information):
N/A

Additional context
those emotes where removed year(s) ago

**Comment by Lordmau5** [comment]
Fixed in the newest FFZ:AP BetterTTV Emotes version
