### ISSUE TITLE
[First Message Highlighter] [Feature Request] On/Off toggle

### ISSUE THREAD

**Issue by SergioVJr** [FrankerFaceZ/Add-Ons#103]
It's distracting to have it enabled in large streams but not in smaller ones, luckily FFZ lets you set profiles for that, but sadly you can't have an add-on enabled in one and not the other. An on/off toggle would allow that.
I did workaround my problem by just making it transparent in the profiles that I didn't want it on, but surely not the best UX when the more elegant solution is so simple.

**Comment by Lordmau5** [comment]
Almost 2 years late to this but seeing as the add-on has expanded with a `First Time Chatter` and `Returning Chatter` highlight option there's now also a checkbox to disable the normal `First Message` highlight it offers
