### ISSUE TITLE
[FS Chat] transparent overlay no longer works for VODs

### ISSUE THREAD

**Issue by necosmo** [FrankerFaceZ/Add-Ons#105]
Transparent overlay still works perfectly during live streams, but completely broken on VODs. I've used the feature many times before, and never had an issue until version 4.32.0 came out recently. I've already tried many different browsers and even disabled other extensions, but couldn't get the transparent overlay to work on VODs at all. 

It was such a great feature. I hope we can find a fix. Thank you so much!

**Comment by SirStendec** [comment]
Closed in c507e5eee654d27c09e431dfe1091b4f7e7070b4
