### ISSUE TITLE
[Deck] Add "Load unfiltered content temporarily"-button

### ISSUE THREAD

**Issue by Taizunz** [FrankerFaceZ/Add-Ons#107]
If you have a column that has filtered out a bunch of content due to clientside filter settings, (i.e blocked categories), there's currently no way to temporarily view the unfiltered results.

I propose the addition of a small button to temporarily view unfiltered content. The button could be added just below the existing end message:
![chrome_2022-03-05_06-21-30](https://user-images.githubusercontent.com/15648000/156869757-782f10ef-b8f7-4796-8215-6b9baf5ee2fd.png)

**Comment by SirStendec** [comment]
Added in eb97fb2dcaa0d8e946c13ba2feef537d2d5af8b1
