### ISSUE TITLE
[Deck] [Feature request] exclude tag from search

### ISSUE THREAD

**Issue by LucilleTea** [FrankerFaceZ/Add-Ons#108]
Hi, just found Deck and I'm loving it, since it seems like twitch no longer allows you to filter by multiple tags in the normal UI. It seems like there's no way to exclude a tag from a search though, which would be really helpful.

I find myself with two columns of combined tag searches, let's say `A + B` and `A + C`. However, most streams which have tag B will also have tag C - it's a kind of subset. The column dedicated to the more specific search is useful to me, but I'd like to avoid showing these results in the column with the broader search. So, a search for `A + C excluding B`.

I saw on another issue that these results are provided by twitch, the search is server side, so I imagine this might require adding a client-side filtering component? Which, I'd understand if you don't want to. Still, it sounds like a useful feature to me.

**Comment by SirStendec** [comment]
Closed in e8a65cadb1bdef04b34078dfb4982a7ad2eae99e
