### ISSUE TITLE
[Deck] [Feature Request] Filter column by game category

### ISSUE THREAD

**Issue by eyriewow** [FrankerFaceZ/Add-Ons#112]
Hi I recently discovered the Deck Add-On and think it's great.

However if it is possible to implement, I would love to be able to filter a column of specific users to only show a stream when the user is streaming is in a specific category, similar to how filtering by tags already works.

I would like this feature because there are streamers that I only follow for their skilled gameplay in a specific game but I don't care much when they are streaming "Just Chatting" or a game I'm not interested in.

**Comment by SirStendec** [comment]
Closed in e8a65cadb1bdef04b34078dfb4982a7ad2eae99e
