### ISSUE TITLE
7TV Emotes add-on does not honor Animated Emotes setting

### ISSUE THREAD

**Issue by dwagner0** [FrankerFaceZ/Add-Ons#113]
I have the Chat » Appearance » Animated Emotes preference set to "Disabled".  I would expect when a 7TV emote is used it would appear statically like all the other emotes (Twitch, BTTV, FFZ) do.  However, instead it still appears animated within chat if the 7TV add-on is enabled.

**Comment by rybak** [comment]
Broken for "Enable on Hover" too. Here's a screen recording:

https://user-images.githubusercontent.com/624072/170131609-2c4bcc6e-be80-45b2-b692-de8c61141f5c.mp4

On the left are two 7TV emotes, on the right are two BetterTTV emotes. I'm moving the mouse up and down between the two messages.

**Comment by SirStendec** [comment]
AFAIK this is more an issue with that service not wanting to provide static images for emotes (which I personally think is totally stupid). Admittedly BTTV doesn't do that either, but FFZ:AP runs a proxy server that removes animation from those emotes.

Something similar could probably be done for 7tv... but their API doesn't to my knowledge differentiate between animated and static emotes? Either way, this is something to discuss with the maintainer @Melonify

**Comment by Melonify** [comment]
In the near future this option will be respected, there is currently a major overhaul of the backend services of 7TV, as part of that update all emotes will have a static version produced and stored. 

It is my intention to add support for the Animated Emotes option once these are generated and live.

**Comment by Lordmau5** [comment]
This still seems to be an issue even with 1.4.0.
From what I can tell the emotes do have a `animated:` value in their object data, but there doesn't seem to be a way to get a static version of an animated emote, or am I mistaken there?

**Comment by Lordmau5** [comment]
Fixed in 36eb69a22b0068c78869499dbee08ba59d52994d
