### ISSUE TITLE
[Deck] - Modal has no max width

### ISSUE THREAD

**Issue by michael-kucek** [FrankerFaceZ/Add-Ons#122]
The modal does not currently have a max width. This means that adding a lot of channels will make the modal grow horizontally with all the channels appearing on one line. By adding a max width, the modal will stay a reasonable width and the content inside will naturally grow vertically. This is more noticeable on higher resolution screens.

I suggest something like this in `/Add-Ons/src/deck/styles.scss`:

```css
.bd-modal {
  max-width: 80rem;
}
```

Before:
<img width="991" alt="Screen Shot 2022-08-03 at 5 28 20 PM" src="https://user-images.githubusercontent.com/3052430/182723491-dddb4f7d-6427-4c4e-b488-a008c925c7f4.png">

After:
<img width="871" alt="Screen Shot 2022-08-03 at 5 31 28 PM" src="https://user-images.githubusercontent.com/3052430/182723631-d51049c8-b4e9-49c6-8252-3c99daac4ae3.png">

I can create a pull request if given access, but this is such a small change that it could definitely piggy back on the next update.

**Comment by SirStendec** [comment]
Fixed in eb97fb2dcaa0d8e946c13ba2feef537d2d5af8b1
