### ISSUE TITLE
FFZ not in the Firefox Addon Store

### ISSUE THREAD

**Issue by PandaSITT** [FrankerFaceZ/Add-Ons#124]
FrankerFaceZ is not in the Firefox Add-on Store (https://addons.mozilla.org/en/firefox/search/?q=FrankerFaceZ&type=extension) or at least not visible. It can still be installed over the website, but it doesn't get synced to other browsers by Firefox.
![grafik](https://user-images.githubusercontent.com/58328398/184736022-f0812995-3a88-488e-9826-068c3e8b5be9.png)

**Comment by Lordmau5** [comment]
From what I know this is because of the fact that the browser extensions of FFZ (for both Chrome and Firefox) are effectively just "script loaders".

They are designed to load the most up-to-date version of FFZ's code when you open a Twitch page.

Firefox's add-on store guidelines prohibit remote code loading which is why it's not listed.

**Comment by CrazyWolf13** [comment]
> From what I know this is because of the fact that the browser extensions of FFZ (for both Chrome and Firefox) are effectively just "script loaders".
> 
> They are designed to load the most up-to-date version of FFZ's code when you open a Twitch page.
> 
> Firefox's add-on store guidelines prohibit remote code loading which is why it's not listed.

Does that also apply for the FFZ Enhancing Add-On ?

Because it's really annoying to always have to reinstall the extensions on a new device, as firefox does not sync extensions which where installed from non addon.mozilla.com domain.

**Comment by Lordmau5** [comment]
We are not affiliated with the Enhancing Add-On and as such can't give any info about that.

The developer of that add-on is free to submit the code to the official FFZ Add-Ons repository so users don't need to install a separate browser extension.
So far, however, they haven't done that.

**Comment by CrazyWolf13** [comment]
@Lordmau5 
Oh yeah sure, sorry abt that. Should've better read lol.

But I've got another question, as you basically stated above, ffz is just a script loader, could it then be loaded as a userscript?

This would massively simplify the process of adding it to a new browser.

Something like here:
https://greasyfork.org/en/scripts/12262-frankerfacez/code
or the ffz ehancer addon: https://tester798.github.io/ffzenhancing/ffzenhancing.user.js

**Comment by Lordmau5** [comment]
Yes? FFZ has pretty much always offered that option and it's gonna stay a valid option especially with Manifest V3 on Chrome dropping soon.

Head to the website, click on the "Other Browsers" dropdown, then click on "User Script"
![image](https://github.com/FrankerFaceZ/Add-Ons/assets/1345036/603592d4-5165-4a00-96e3-b34944c0a26d)
