### ISSUE TITLE
[7TV] Animated emotes resets while being spammed

### ISSUE THREAD

**Issue by Fogo0** [FrankerFaceZ/Add-Ons#127]
GIF emotes are always start at frame one whenever the same emote sent into chat again.

Edit: This issue started when i switched to Firefox, didn't have this issue in Chrome.

**Comment by Fogo0** [comment]
Setting Hardware acceleration to always on seems to fix the issue.

**Comment by Fogo0** [comment]
Problem still persists even after enabling hardware acceleration.

**Comment by Lordmau5** [comment]
From what I know this is an issue with Firefox itself that can't easily be fixed.

For more information check this issue here: https://github.com/FrankerFaceZ/FrankerFaceZ/issues/985
