### ISSUE TITLE
[First Message Highlighter] [Bug/Feature]

### ISSUE THREAD

**Issue by CrazyWolf13** [FrankerFaceZ/Add-Ons#132]
I enabled the setting: "pin mentioned messages" so every message containing @{myusername} gets pinned in the chat but if i enable "first message highlighter" every new message gets pinned even from users who did not mention me with @{myusername}
Its quite annoying lol would be great if there would be an option to just set a color for first message addon.

**Comment by Lordmau5** [comment]
Which addon are you seeing the setting "Pin Mentioned Messages" from?

The only one I can find is Smokey's Utilities and that has a configurable list of Pin Reasons:
![image](https://user-images.githubusercontent.com/1345036/197387150-6d98b6e8-5046-4fcd-9075-179b4f70ed08.png)

**Comment by CrazyWolf13** [comment]
In the FFZ Enhancing Add-On 
![image](https://user-images.githubusercontent.com/96661824/197387224-c9918759-0934-4585-ad93-c076c8dd7dd6.png)


> Which addon are you seeing the setting "Pin Mentioned Messages" from?
> 
> The only one I can find is Smokey's Utilities and that has a configurable list of Pin Reasons: ![image](https://user-images.githubusercontent.com/1345036/197387150-6d98b6e8-5046-4fcd-9075-179b4f70ed08.png)

**Comment by CrazyWolf13** [comment]
Thanks this already solved my issue i will now use Smokey's ulities :) seems to work fine.^^

**Comment by Lordmau5** [comment]
Glad to hear it solved the issue!
