### ISSUE TITLE
[PrattleNot] [Feature request] Be able to filter users that are not following

### ISSUE THREAD

**Issue by tballas** [FrankerFaceZ/Add-Ons#134]
I often click on usernames to see if a user is following a channel to see if it's likely a relevant message or not. It would be nice to be able to filter users that are not following as Prattle.

**Comment by SirStendec** [comment]
This is not possible without a prohibitive number of API requests. Chat messages do not include a flag for if the user is following or not. It's not something I'm willing to implement.
