### ISSUE TITLE
[Pronouns] [Bug] Pronoun Badge is displayed incorrectly only when using the Add-On

### ISSUE THREAD

**Issue by Muphinnz** [FrankerFaceZ/Add-Ons#136]
![mrpRIYk2](https://user-images.githubusercontent.com/122409024/211678940-bade07b3-d241-4a51-b1cd-1edd5e67f12f.png)
When using the Add-On version of Pronouns the badge seems to get stuck right behind your Global badge, while channel-specific badges (sub, mod, broadcaster, etc) are properly displayed to the left.

![image](https://user-images.githubusercontent.com/122409024/211679896-84515701-aa4c-4c66-99cf-56d0c82df5d9.png)
After disabling the Add-On and going to download the browser extension instead the Pronouns badge is properly displayed as the furthest right badge, which makes it much easier and quicker to read + process at a glance.

This visual bug happens for all chatters in all chats from what I could tell, but didn't get a screenshot for those.

**Comment by Lordmau5** [comment]
It could very well be that increasing the `slot` value [here](https://github.com/FrankerFaceZ/Add-Ons/blob/master/src/pronouns/index.jsx#L206) should be able to bring it to the furthest position on the right.

Right now it's at `40`, I don't know what Twitch's default is (or FFZ considers as default by Twitch) - maybe `51` would already fix that. Alterantively, `999` haha
