### ISSUE TITLE
Smokey's Utilities Pin Mention broken

### ISSUE THREAD

**Issue by CrazyWolf13** [FrankerFaceZ/Add-Ons#137]
Pin mention does not work even tough it's enabled. Working till yesterday.
Hope for a quick answer, thank you.

**Comment by CrazyWolf13** [comment]
![image](https://user-images.githubusercontent.com/96661824/212501541-ab0515a4-3e5f-4752-81ea-b263b923327c.png)
![image](https://user-images.githubusercontent.com/96661824/212501543-3ea89cfa-2843-48d9-9d10-2d7a80cbee53.png)

Hope this helps.

**Comment by CrazyWolf13** [comment]
FFZ is loaded at the time of the screenshot being taken

**Comment by Physikbuddha** [comment]
I can confirm that the feature stopped working yesterday.

Doesn't work anymore on multiple browsers tested (Chrome, Firefox, iOS-Safari).

**Comment by CrazyWolf13** [comment]
> I can confirm that the feature stopped working yesterday.
> 
> Doesn't work anymore on multiple browsers tested (Chrome, Firefox, iOS-Safari).

Thank you for confirming

**Comment by Balentay** [comment]
Came here to +1 confirm as well.  Suddenly broke for me yesterday.  Additionally I've tried clearing my cache, installing a fresh profile, a fresh instance of FFZ, and clearing my FFZ data

**Comment by CrazyWolf13** [comment]
@smokey019 May you look into this?

**Comment by smokey019** [comment]
did a PR for it just now, should be good to go whenever it gets approved! 


sorry for taking so long. new pc and had to setup all the dev environment stuff again XD

**Comment by CrazyWolf13** [comment]
> did a PR for it just now, should be good to go whenever it gets approved!
> 
> sorry for taking so long. new pc and had to setup all the dev environment stuff again XD

No problem, you don't have to apologize. Thank you for the quick answer and for already making a pr. 
Just out of curiosity why did this break just out of nowhere, is that twitch related?

**Comment by smokey019** [comment]
> > did a PR for it just now, should be good to go whenever it gets approved!
> > sorry for taking so long. new pc and had to setup all the dev environment stuff again XD
> 
> No problem, you don't have to apologize. Thank you for the quick answer and for already making a pr. Just out of curiosity why did this break just out of nowhere, is that twitch related?

tbh not entirely sure. it was hooking onto the first element in the chat and i believe that is what broke. so very likely a twitch issue that effected it somehow.

**Comment by Balentay** [comment]
![image](https://user-images.githubusercontent.com/37963727/213875499-fc094e6c-dde8-4885-8eed-ee0834001c2a.png)

It seems like pinned messages are really tiny now?  I have chat font size set to 18 and there is a marked difference in size between chat messages and pinned messages

**Comment by smokey019** [comment]
> ![image](https://user-images.githubusercontent.com/37963727/213875499-fc094e6c-dde8-4885-8eed-ee0834001c2a.png)
> 
> It seems like pinned messages are really tiny now? I have chat font size set to 18 and there is a marked difference in size between chat messages and pinned messages

i think it's just not picking up the chat style. i'll take a look into this right now.

**Comment by Lordmau5** [comment]
From what I can tell pinned messages are working again, so can this be closed?

Just double-checking

**Comment by CrazyWolf13** [comment]
> From what I can tell pinned messages are working again, so can this be closed?
> 
> Just double-checking

On my end it's working again, but they are overlapping the top cheer board, don't know if this is intended. But thank you very very much fox fixing this so quickly. ^^

**Comment by smokey019** [comment]
It's working again so this can be closed. I will consider cleaning it up and putting mentions in a better spot but for now this will work.

As far as the font size goes, I'm not sure why it isn't working because it should be the same CSS class as a message and I can't see a difference but I may have to add a setting for font size for my addon in particular later.
