### ISSUE TITLE
Restoring FFZ settings breaks FFZ AP

### ISSUE THREAD

**Issue by piebandit** [FrankerFaceZ/Add-Ons#14]
When I restore my FFZ settings it completely breaks FFZ AP. The only setting sub-sections in FFZ Settings that appear under Add-Ons is Changelog and FFZ:AP Core, the rest disappear and BTTV Emotes no longer appear in chat or in the emote menu.

The only way I've found to fix it is to clear local storage data, uninstall FFZ AP and reinstall.

The issue is repeatable by importing settings again.

Log: https://www.piebandit.tv/share/ffzlog.txt

**Comment by SirStendec** [comment]
When you're talking about installing FFZ AP are you talking about the browser extension? FFZ:AP uses FFZ's Add-ons list now, so you need to enable the parts you want in the FFZ Control Center's Add-ons list now.

Restoring a full settings dump will also restore the list of active add-ons, thus disabling add-ons that weren't enabled at the time the dump was made.

**Comment by piebandit** [comment]
Yes, the browser extension. When I restore full settings dump the FFZ:AP settings in FFZ Control Center disappear and it no longer functions.

**Comment by piebandit** [comment]
I'm able to replicate this in a different chrome profile.

1. Install FFZ and FFZ:AP from chrome webstore
2. Change FFZ Settings
3. Create FFZ Settings Dump
4. Restore FFZ Settings Dump
5. FFZ:AP stops functioning

My settings dump file: https://www.piebandit.tv/share/ffz-settings%20%281%29.json
![chrome_2020-04-26_14-43-37](https://user-images.githubusercontent.com/48078984/80320942-4b9fd480-87ce-11ea-986f-c1e02f741a79.png)
![chrome_2020-04-26_14-44-10](https://user-images.githubusercontent.com/48078984/80320937-43e03000-87ce-11ea-9bd9-dc33e43d3347.png)

**Comment by Lordmau5** [comment]
It has been over 2 years since this issue was made and FFZ has seen various commits since then so I'm closing this issue under the assumption that it's fixed (or at least not an issue anymore?)
