### ISSUE TITLE
[Bug] Modifiers doesn't respect FFZ large emote setting

### ISSUE THREAD

**Issue by RedSnt** [FrankerFaceZ/Add-Ons#145]
The setting "FFZ control center -> Chat -> Appearance -> Larger emotes" set to either "Emotes" or "Emotes & Emojis" is ignored when using modifiers. The modified emotes are regular sized and not scaled up. 
![image](https://user-images.githubusercontent.com/6242718/223480006-88e889f4-197e-4a22-a469-85a3d39c3ec0.png)

**Comment by Lordmau5** [comment]
This should be fixed in the newest release of FFZ, can you check again?

**Comment by RedSnt** [comment]
Yup, this is now fixed 👍 Thanks a bunch.
