### ISSUE TITLE
[BetterTTV Emotes] Not all modifiers being applied

### ISSUE THREAD

**Issue by Sheigutn** [FrankerFaceZ/Add-Ons#148]
FFZ:AP BTTV:
![chrome_2023-03-08_21-10-50](https://user-images.githubusercontent.com/5239767/223840211-cd2e31f4-0784-4a7c-a0e3-b9d0ae9afa2a.png)

BetterTTV:
![chrome_2023-03-08_21-15-07](https://user-images.githubusercontent.com/5239767/223840214-46ea312c-34f0-48a4-b68c-ef2a8683a86f.png)

Same thing also happens with v! and h!, but not with !z.

**Comment by Lordmau5** [comment]
I'm not 100% sure I can follow what the result should be

Are you able to chain multiple `w!` modifiers with BTTV? Or is it only doing the first `w!` but not the other ones?

**Comment by Sheigutn** [comment]
It's the latter, the input is this: `w! KKool w! KKool w! KKool w! KKool w! KKool`. 
While the actual BTTV extension widens every single emote, the FFZ BTTV only does the first one. I'm thinking this is because of the switch only checking the `'w! '` case, not `' w! '` (or just trimming the spaces completely).

**Comment by Lordmau5** [comment]
I see what you mean! Also had a suggestion from another user to allow chaining of the modifiers (so `w! h! v! EMOTE` for example) so that's in as well as of 3.3.6 :)
