### ISSUE TITLE
[BetterTTV Emotes] 'w!', 'h!', 'v!' modifiers don't work if used after some plain text

### ISSUE THREAD

**Issue by tihasdop** [FrankerFaceZ/Add-Ons#149]
Test messages:
`w! KKona`
`test w! KKona`

BTTV:
![bttv](https://user-images.githubusercontent.com/6596067/224355597-9143b1a3-f68d-47e0-9f97-5cd834af9efa.png)

FFZ:AP BTTV:
![ffz](https://user-images.githubusercontent.com/6596067/224355602-2f0b4290-cde6-4f41-9903-f8137800b79b.png)

Same with `h!` and `v!`, but `z!` works correctly.

**Comment by Lordmau5** [comment]
known issue, fixed in the next release, just waiting for some extra stuff from Stendec's side for base FFZ :D

**Comment by Lordmau5** [comment]
Should be resolved by 3.3.8 :) If more issues come up please open a new one
