### ISSUE TITLE
[Deck] - Add usage of custom tags

### ISSUE THREAD

**Issue by CreeperChief** [FrankerFaceZ/Add-Ons#151]
Currently you can only use tags from a predefined list of tags, but streamers have the ability to create custom tags not in the list.

As an example, when I tried to filter my followed channels with the Vtuber tag (with capital V),  only a few channels showed up on the column because most of them use the vtuber tag (with non - capital V).

**Comment by w4tchdoge** [comment]
I'm experiencing the same/similar issue where tag filtering on Deck seems to just be broken.
For example, if I set up a new column in Deck [for Art streams with the `Vtuber` tag](https://i.imgur.com/YiYVKbI.png) nothing shows up, but if I go to Twitch's Category page for Art and [use the built-in tag search bar to looks for streams with the tag `Vtuber`](https://i.imgur.com/WvtBpB3.png) I can see streams where the "V" is capitalised and ones where it isn't.

**Comment by SirStendec** [comment]
Fixed in the last update
