### ISSUE TITLE
[Fullscreen Chat] Enabling background blur disables Nvidia VSR

### ISSUE THREAD

**Issue by arturino009** [FrankerFaceZ/Add-Ons#154]
Enabling any amount of background blur disables Nvidia VSR for the stream. There is a visible difference on my screen when it is active (and the GPU wattage and usage also indicates that).
An icon from stream with overlay enabled:
![image](https://user-images.githubusercontent.com/51629394/229137748-6f37853d-35f9-4717-9d1f-ec7232859d38.png)
An icon from same stream with overlay disabled:
![image](https://user-images.githubusercontent.com/51629394/229137937-6f56c3f3-3480-419e-aca5-afebec14a475.png)

Fullscreen Chat version: 1.5.0
Chrome version: Version 111.0.5563.147 (Official Build) (64-bit)
FrankerFaceZ version: 4.45.0

**Comment by SirStendec** [comment]
There is absolutely nothing that we can do about that. Whether or not something like that is used is entirely down to implementation details of your browser and Nvidia's software.
