### ISSUE TITLE
[Clip Confirm] not working

### ISSUE THREAD

**Issue by Breetlez** [FrankerFaceZ/Add-Ons#155]
I tried clip confirm on both of my browsers firefox and chrome. there is no confirmation prompt showing up. it creates the clip immediately.

Both my browsers and FFZ updated to the last version.

**Comment by argowizbang** [comment]
What channel is this happening on?

**Comment by Breetlez** [comment]
> What channel is this happening on?

to all channels but i figured out how to produce this problem. it won't work if you browse channels. like after i join any channel I need to refresh every time to work. is a small gif explain it more. [https://streamable.com/3ct180](url)

**Comment by argowizbang** [comment]
Perfect, thank you! I'll see about getting this fixed ASAP.
