### ISSUE TITLE
[7TV Emotes] Live Emote Updates Not Working

### ISSUE THREAD

**Issue by dpthegrey** [FrankerFaceZ/Add-Ons#157]
Live Emote Updates is Enabled but still addtion or removal of emotes are not showing in chat and need a refresh to show up recently added emotes.

![image](https://user-images.githubusercontent.com/49444980/231715516-f59bb3c4-3999-45b3-be3f-55771dbe2245.png)

FFZ Version: Version 4.45.1 [3d4b4f6](https://www.github.com/FrankerFaceZ/FrankerFaceZ/commit/3d4b4f62253049feb5b7bf43a8f9a44b5d378225)
Browser: Brave Browser (1.50.114 Chromium: 112.0.5615.49 (Official Build) (x86_64))

**Comment by barnumbirr** [comment]
[7TV's EventAPI v1 is now deprecated,](https://github.com/SevenTV/EventAPI#versions) hence the broken feature. v3 of the events API uses the SSE mechanism so this will probably require substantial changes to the add-on.

**Comment by coldino** [comment]
It looks like the current code already uses SSE (https://github.com/FrankerFaceZ/Add-Ons/blob/master/src/7tv-emotes/modules/eventapi.js#L51), but the new API works differently.

My take on some of the details that might need to change to make this work:

*(I use a `:param` format for parameter replacement)*

* Before subscribing to events you need to look up the relevant emote set ID for the channel, by channel ID (not name), from `https://7tv.io/v3/users/twitch/:userid`, looking through `user.connections` for `platform: "TWITCH"`, then grab `emote_set.id`. Maybe there's a direct way by channel name, but I couldn't find it.

* Create an SSE address with emote_set event filter e.g. `https://events.7tv.io/v3@emote_set.update<object_id=:emote_set_id>` (yes, that's a `@` and a `<>` pair!).

* Modify the event handling. The `dispatch` event contains `{type:"emote_set", body: ...}`, where the body is presumably vaguely equivalent to what was recieved before. `actor` looks the same, but potentially multiple emotes are `pulled` or `pushed` out of or into emote sets now.

**Comment by barnumbirr** [comment]
I have no idea why or how but it would seem that live emote updates for 7TV are back, at least for me.

**Comment by coldino** [comment]
Indeed, something changed on the 7tv side. Previously this request was returning some 300 error (can't remember which one). Now it's returning 429 (Too Many Requests) despite this being the first time I've touched the service today. So still doesn't work for me, but something is different for sure.

**Comment by GdotRU** [comment]
Still seems to be an ongoing issue.
