### ISSUE TITLE
update broke fs chat

### ISSUE THREAD

**Issue by X2E4VXpZKv** [FrankerFaceZ/Add-Ons#163]
twitch made some changes to the fullscreen layout and fullscreen chat now doesnt appear. it also breaks the sidebar chat in fullscreen when enabled.
i kindly ask you to fix it if you have the time, its really useful to have chat as an overlay on smaller monitors.

**Comment by DarkCeptor44** [comment]
It's back to working again.

**Comment by de1337ro** [comment]
It is still nog working for me (Firefox, macOS)
