### ISSUE TITLE
[Deck] [Feature request] Auto Extend Sidebar (show more)

### ISSUE THREAD

**Issue by Fujosej** [FrankerFaceZ/Add-Ons#164]
Hi , would be nice to have an auto extend feature for the following list , when using deck as a sidebar ![image](https://github.com/FrankerFaceZ/Add-Ons/assets/37980944/3646dd20-3c18-407c-b29c-881ccb68a922).
![image](https://github.com/FrankerFaceZ/Add-Ons/assets/37980944/f8f103bc-69b3-4227-8654-91f83a32d333)

**Comment by SirStendec** [comment]
When you're editing a sidebar entry for Deck, you can choose how many items appear by default using the Default Size option. There's no need for something to automatically hit "Show More" when it can just be set to use more from the start.
![image](https://github.com/FrankerFaceZ/Add-Ons/assets/14036657/1e5adb3e-8592-493d-a405-11cd7142bf52)

(This did make me notice a bug though, where the default value of the UI is "10" but the default value of the loading logic is "5", so I'll be fixing that in the next Deck update.)
