### ISSUE TITLE
[Safari] 7TV Access-Control issues

### ISSUE THREAD

**Issue by KDederichs** [FrankerFaceZ/Add-Ons#165]
Hey,
I'm using FFZ in Safari (via Tempermonkey) at it seems like it's running into CORS issues with 7TV since it's spamming my log with this:
![Screenshot 2023-06-13 at 21 47 35](https://github.com/FrankerFaceZ/Add-Ons/assets/24696606/0c0b3e68-2a26-4d8d-bce8-938e235800ce)

Not sure if that's something you can influence or if the 7TV folks need to set the Access-Control-Allow-Origin header

**Comment by Lordmau5** [comment]
Could you test if this issue is still present with the newest 1.4.0 update to the 7TV add-on?

**Comment by KDederichs** [comment]
Seems fixed 👍
