### ISSUE TITLE
[Deck] Stream tags functionality broken

### ISSUE THREAD

**Issue by DeviousLab** [FrankerFaceZ/Add-Ons#167]
Currently stream tags do not appear on any streams fetched in a panel. 
This also breaks the stream tag filtering system. 
Tested on both Chromium and Firefox browsers with adblock disabled.
![mhz3hEY](https://github.com/FrankerFaceZ/Add-Ons/assets/53790060/20b4d593-fc7d-49a3-abbd-a3d795145b89)
Another user is facing a similar issue:
>  I'm experiencing the same/similar issue where tag filtering on Deck seems to just be broken.
> For example, if I set up a new column in Deck [for Art streams with the `Vtuber` tag](https://i.imgur.com/YiYVKbI.png) nothing shows up, but if I go to Twitch's Category page for Art and [use the built-in tag search bar to looks for streams with the tag `Vtuber`](https://i.imgur.com/WvtBpB3.png) I can see streams where the "V" is capitalised and ones where it isn't.
> 
> _Originally posted by @w4tchdoge in https://github.com/FrankerFaceZ/Add-Ons/issues/151#issuecomment-1572677896_

I'd assume that this is a breaking change from the Twitch API, as stream tags function fine on the site itself.

**Comment by DeviousLab** [comment]
https://dev.twitch.tv/docs/api/reference/#get-stream-tags states:
> IMPORTANT Twitch is moving from Twitch-defined tags to channel-defined tags. IMPORTANT As of February 28, 2023, this endpoint returns an empty array. On July 13, 2023, it will return a 410 response. If you use this endpoint, please update your code to use [Get Channel Information](https://dev.twitch.tv/docs/api/reference/#get-channel-information).

**Comment by SirStendec** [comment]
Fixed in 1163635f5eb9fa13eaff6c8f3b9c2fdb6184abc9
