### ISSUE TITLE
Remaining 7TV issues (post-PR)

### ISSUE THREAD

**Issue by Lordmau5** [FrankerFaceZ/Add-Ons#169]
As @crashmax-dev mentioned in their pull request #168 there are still some features that don't seem to work quite yet with the new 7TV API (at least in their testing).

To quote:

## *Help wanted*
- *I don't know if nametag paints works.*
- *Not working 7tv cosmetics.*

___

This issue is mostly for organizational purposes. If someone would be willing to look into this a PR is more than welcome! :)

**Comment by jjjj222** [comment]
Maybe not related to this issue, but all the 7tv emotes are not shown anymore in Twitch chat after this update.

**Comment by xopuk** [comment]
Same, 7tv emotes don't work and it looks like it's related - newly added emotes are showing, but after refresh they are also gone.

**Comment by Satont** [comment]
I do not see such problem, works for me.
![image](https://github.com/FrankerFaceZ/Add-Ons/assets/42675886/f33211a1-419b-407c-92c0-643f5ae4a350)

**Comment by Lordmau5** [comment]
@jjjj222 @xopuk This should be fixed in 1.3.2 - there was an issue with certain emotes not having a display name and it was causing the function to add the emotes to not work at all

Can you guys please check again and report back?

**Comment by xopuk** [comment]
Yeah seems to be fixed now, thanks!

**Comment by jjjj222** [comment]
It works now. Thanks.

**Comment by mbrigdan** [comment]
Last I checked, 7tv personal emotes weren't working. That's probably a bigger change, depending on if the BTTV personal stuff can be (ab)used ? I'll try to look into it in a week or so when I've got some time.

**Comment by Lordmau5** [comment]
Should be resolved by 8c8f10f994e396dc888466fa70cf822c572efb26

If there are any more issues, I encourage everyone to open fresh issues :)
