### ISSUE TITLE
FFZ:AP Core "Enable Highlight Sound" plays twice

### ISSUE THREAD

**Issue by bottleblue** [FrankerFaceZ/Add-Ons#171]
I have it set to play a sound when a highlighted term is triggered. A few weeks ago it started doing this thing where half the time it plays the sound twice, over each other. It happens with single or multiple highlighted terms. It happens with preset sounds or custom files. I've tried removing APCore and local storage files. I tried changing storage providers between IndexedDB and Local Storage. 

It seems to happen more often when there's a repeat of the same triggered word. Like if there's a Marbles race going on and everyone types !play it's more likely to do the double sound consistently.

**Comment by bottleblue** [comment]
After some testing I found the problem is caused by the Chrome addon "Twitch chat overlay on fullscreen".  Maybe FFZ AP Core is counting the highlighted word twice from the chat overlay. It happens even when I don't have the chat overlay on though. Disabling the addon stops the double audio so I have to assume this is causing it.

**Comment by Lordmau5** [comment]
It could be that the Chrome addon you mention adds a completely separate chat instance on-top of the fullscreen stream (maybe all the time so it gets messages in the background) causing FFZ to effectively load twice.

Have you considered using the Fullscreen Chat add-on from within FFZ instead or does that cause some issues for your use-case?
![image](https://github.com/FrankerFaceZ/Add-Ons/assets/1345036/7a6ddee1-7945-44cf-90aa-85061ab64b24)

**Comment by bottleblue** [comment]
yes I have Fullscreen Chat also. The other addon has some options that Fullscreen chat didn't so I kept both but I can do without the chrome addon. Honestly I don't use the chat overlays a whole lot it was just nice to have.
