### ISSUE TITLE
[BetterTTV Emotes] New emote modifiers 'c!', 'l!', 'r!'

### ISSUE THREAD

**Issue by Lordshinjo** [FrankerFaceZ/Add-Ons#173]
In BetterTTV releases 7.5.4 and 7.5.5, 3 new emote modifiers have been added, see [js](https://github.com/night/betterttv/blob/ddd9e4937c0984dbbaa9cb176039161acd17378c/src/modules/chat/index.js#L31-L33) and [css](https://github.com/night/betterttv/blob/ddd9e4937c0984dbbaa9cb176039161acd17378c/src/modules/chat/style.css#L32-L39):
* `c!`: same as `ffzCursed`
* `l!`: static `-90deg` rotation
* `r!`: static `90deg` rotation

`c!` should be pretty easy to add, not sure about `!l` and `!r` though (e.g. would you add them to the available FFZ modifiers, keep them only for BTTV?)

**Comment by Lordshinjo** [comment]
As of 3.3.18 I guess this can be closed even though the rotations are not fully implemented yet.

**Comment by Lordmau5** [comment]
Rotations need the corresponding modifiers to also be available in base FFZ, but the code for it is already in place, meaning that once base FFZ adds those modifiers they should start working for BTTV's `l!` and `r!` as well :)
