### ISSUE TITLE
Deck - Option to hide broadcasts that haven't selected a category

### ISSUE THREAD

**Issue by Taizunz** [FrankerFaceZ/Add-Ons#178]
I'd like to request the addition of an option in the Deck plugin that makes it possible to filter channels out if they aren't in any category.

Some broadcasters remove their channel from categories when they sleep on stream, do re-runs, etc., and having a way to remove these on Deck columns and/or tabs would be great.

**Comment by SirStendec** [comment]
Added in eb97fb2dcaa0d8e946c13ba2feef537d2d5af8b1
