### ISSUE TITLE
7TV - Group subscriber badges

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/Add-Ons#180]
I think it would be a good idea to combine the 7TV subscriber badges into one group on the visibility screen, due to the fact that new subscriber tenure badges are being adding at a semi-frequent interval. This would bring the behaviour more in line with the official Twitch channel subscriber group. Leaving the `7TV Subscriber (Founder)` badge separate from this proposed group would also more closely follow the official behaviour.

Thanks,
pointy

**Comment by Lordmau5** [comment]
Fixed in 8c8f10f994e396dc888466fa70cf822c572efb26
