### ISSUE TITLE
feature request; flag messages

### ISSUE THREAD

**Issue by Trebian1** [FrankerFaceZ/Add-Ons#192]
Hello,
I would like to make a feature request.

I miss the ability to flag first messages after a selectable time, e.g. when chatters don't say anything for a long time but then join the chat again.

Thank you for editing.
Best regards
Trebian

Hallo,
ich würde gern eine Feature-Anfrage stellen.

Ich vermisse wie Möglichkeit, erste Nachrichten nach einer wählbaren Zeit zu Flaggen.
Z.B. wenn Chatter*innen eine Zeit lang nichts sagten, sich dann aber wieder in den Chat einbringen. 

Danke für die Bearbeitung.
Freundliche Grüße

**Comment by Lordmau5** [comment]
So I have some WIP code for this implemented in a local version of the First Message Highlighter.
Seemed like the best place to put it since it already highlights the very first message in the session.

![image](https://github.com/FrankerFaceZ/Add-Ons/assets/1345036/49db817b-a9ae-4719-bf63-cf47e114f0e8)
![image](https://github.com/FrankerFaceZ/Add-Ons/assets/1345036/76f915b2-d859-4731-8429-dc48295d3feb)

If @akshualy would be okay with that I could make a PR for it (or just commit it directly) :)

**Comment by Trebian1** [comment]
You are awesome!  🤗 
Thank you  👍

**Comment by Lordmau5** [comment]
Small update on this: I changed my code a bit and now it doesn't work at all. I officially hate JavaScript and it's reference design.

Still, I wouldn't push anything to the addon if I akshualy isn't fine with it, so that gives me some more time 🤣

**Comment by akshualy** [comment]
> So I have some WIP code for this implemented in a local version of the First Message Highlighter. Seemed like the best place to put it since it already highlights the very first message in the session.
> 
> ![image](https://private-user-images.githubusercontent.com/1345036/291380890-49db817b-a9ae-4719-bf63-cf47e114f0e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDEyMjgsIm5iZiI6MTcwMzAwMDkyOCwicGF0aCI6Ii8xMzQ1MDM2LzI5MTM4MDg5MC00OWRiODE3Yi1hOWFlLTQ3MTktYmY2My1jZjQ3ZTExNGYwZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTU0ODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU0M2U3ODgzZTVhZGE4ZTAxNTU4OTQxNWEyN2I4YTAyOWY2NzljMTVlMTUwZmQ4YjY2Yjc1NmNiYTViYjRmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X9U5ESSo66FqruIBot1Rgpoac96w32ABFkq5dcGGJ7A) ![image](https://private-user-images.githubusercontent.com/1345036/291380908-76f915b2-d859-4731-8429-dc48295d3feb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDEyMjgsIm5iZiI6MTcwMzAwMDkyOCwicGF0aCI6Ii8xMzQ1MDM2LzI5MTM4MDkwOC03NmY5MTViMi1kODU5LTQ3MzEtODQyOS1kYzQ4Mjk1ZDNmZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTU0ODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWEwYzE4NWFkZjg1NjdiNDQ5OTM3YjQwNGIwNWE0OWU2NDQ0ODQ4Nzk1ZTI1MWJhYTQ0OTRmZmEzYjczOGY1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zGq7cUn45qvPkn76VzElaNtBiVtq3nz2Z2almeIhkno)
> 
> If @akshualy would be okay with that I could make a PR for it (or just commit it directly) :)

go ahead, I have nothing against it :)

**Comment by Trebian1** [comment]
Thank you 🤗 
I wish  you a merry christmas 🎄  🎁   🕯️  🍬

**Comment by Lordmau5** [comment]
Likewise! Please report any issues you encounter with it - during my testing I didn't spot anything out of the ordinary, but that was just a test-case of 1. Now that it's out in the wild I assume there might be more 😁
