### ISSUE TITLE
7tv Paints randomly vanish

### ISSUE THREAD

**Issue by TheRealDadbeard** [FrankerFaceZ/Add-Ons#194]
Since a couple of weeks now paints randomly vanish and come back after the user has written again, Badges are loaded wrong too.

**Comment by Lordmau5** [comment]
That's a 7TV issue. I've implemented the socket events according to spec.
(As in, if I get a "add cosmetics" event, I'll add it to a user. If I get a "remove cosmetics" event, I'll remove it from a user)

I'm not quite sure *why* it happens in their backend but if there's something I can do to maybe work around it I'd be happy to implement it.

cc @Melonify

**Comment by TheRealDadbeard** [comment]
> After looking at their code again the only difference I could see was that they are sending at most one presence message every 10 seconds, instead of on every chat message by the user.
> 
> I've implemented that as well in 1.4.18, maybe that'll help with the problem?
> 
> I'll leave the issue open for now, maybe Melonify can chime in with some extra thoughts (or perhaps he can have another look at the code) because this most definitely is an issue on their end

Seems to be broken again. It was better before but now I very rarely get my paint shown.

**Comment by Lordmau5** [comment]
7tv issue as per usual

**Comment by Lordmau5** [comment]
I've not had any more reports of this happening ever since they've changed up their infrastructure so I'm gonna go ahead and close this now

If this issue does pop up again feel free to open a new issue
