### ISSUE TITLE
[FS Chat] Enter button doesn't send message

### ISSUE THREAD

**Issue by TemporaryCrown** [FrankerFaceZ/Add-Ons#218]
Enter button doesn't work to send a message it just brakes the chat box text on edge and chrome.

https://github.com/FrankerFaceZ/Add-Ons/assets/77809605/4b68b2d5-78ae-47e2-8aa3-3155302cdccc

**Comment by Tai-Mai** [comment]
This is a duplicate of #217

**Comment by TemporaryCrown** [comment]
Its only for the Fullscreen video chat not the twitch chat text box. The original chat text box works fine when pressing enter

**Comment by Tai-Mai** [comment]
Yes, this has also already been commented before. https://github.com/FrankerFaceZ/Add-Ons/issues/217#issuecomment-2105957587

**Comment by RYJASM** [comment]
> Yes, this has also already been commented before. [#217 (comment)](https://github.com/FrankerFaceZ/Add-Ons/issues/217#issuecomment-2105957587)

It's till an issue.

**Comment by spxplucky** [comment]
I have the same problem.

**Comment by SirStendec** [comment]
Duplicate of #217
