### ISSUE TITLE
Fullscreen Chat: Resizing the window makes the chat overlay inaccessible to grab

### ISSUE THREAD

**Issue by RYJASM** [FrankerFaceZ/Add-Ons#224]
Repeatable issue: Drag chat overlay to X side (top, left, right, bottom) of screen. Drag X side of window to make the window smaller and hide the chat overlay. You will be unable to see or grab the full screen chat overlay.

Expected result: Overlay window would stay visible at all times and move or shrink with the window if the window got smaller than the overlay.

**Comment by SirStendec** [comment]
Duplicate of #217
