### ISSUE TITLE
Clip confirm in the player mode

### ISSUE THREAD

**Issue by x9136** [FrankerFaceZ/Add-Ons#232]
Most often I watch streams on the player page: https://player.twitch.tv/?channel=forsen&parent=twitch.tv. If possible, it would be convenient for Clip Confirm to work in this case.

**Comment by argowizbang** [comment]
I'll look into this, but I can't make any guarantees because it may or may not take a decent amount of work to make happen. But I'll see what I can do!

**Comment by x9136** [comment]
@argowizbang I don't know if you've seen it or not, but Twitch has updated the clip creation page. Now you can easily cancel the creation of the clip. My request is non-relevant now. You can close it if you agree.

**Comment by argowizbang** [comment]
Yes, I had been waiting for that update to be pushed on Twitch so I definitely noticed when they finally made it live!

I don't actually have any authority in the Add-Ons repository itself so I can't close the issue myself but I'll make a mental note that this is no longer necessary to work on.
