### ISSUE TITLE
[Smokey's Utilities] Pinned Mentions no longer showing properly

### ISSUE THREAD

**Issue by DeltaLeeds** [FrankerFaceZ/Add-Ons#237]
Pinned mentions are covered by gift / cheer leaderboards and are also covered by chat.
![image](https://github.com/user-attachments/assets/db83839e-2a4f-4b27-85d4-0d30afe29366)

**Comment by smokey019** [comment]
https://github.com/FrankerFaceZ/Add-Ons/pull/238 this should fix it whenever it gets merged
