### ISSUE TITLE
Shared Chat Emote Lists Lack Channel Identifier

### ISSUE THREAD

**Issue by traitorValkyrie** [FrankerFaceZ/Add-Ons#250]
Looking at a shared chat today, I was struggling to be able to tell which channel owns which list of emotes (as shown in the screenshot below).  For context, I am a channel mod and we were trying to identify the origin of some emotes from a shared chat.

![FFZ emote list for shared chat](https://github.com/user-attachments/assets/ebc38c9a-7f3b-4249-b377-0855d7593d5f)

While the FFZ lists are separated and labelled, the 7tv and BTTV lists lack a channel name to help us quickly know which list belongs to which channel.

Couldn't find any settings to be able to better tell who had what.  I'm assuming it might be alphabetical for the list of streams in the shared chat, but it would still be nice to have something visual on the tabs to know.

**Comment by SirStendec** [comment]
Implemented in today's combined FFZ + add-ons update.
