### ISSUE TITLE
I can't tell if this is intentional or not, but pronouns have weird placement

### ISSUE THREAD

**Issue by brian6932** [FrankerFaceZ/Add-Ons#52]
Pronoun placement is a little weird with Twitch badges
![image](https://user-images.githubusercontent.com/18603393/109745520-fe388480-7ba1-11eb-8f54-c8071185765b.png)
![image](https://user-images.githubusercontent.com/18603393/109745059-50c57100-7ba1-11eb-89f1-10072c170d22.png)

Looks fine without Twitch badges though:
![image](https://user-images.githubusercontent.com/18603393/109745699-435cb680-7ba2-11eb-9529-c3048501c6e2.png)
The [original project](https://github.com/Alejo47/chat_pronouns_browser_extension) does not exhibit this

**Comment by Lordmau5** [comment]
I think this was resolved by #136 already, so I'm gonna close this issue.

If it comes up again please create a new one
