### ISSUE TITLE
Highlighted users no longer got pinned to top of chat

### ISSUE THREAD

**Issue by ghost-20** [FrankerFaceZ/Add-Ons#59]
Pinned mention option in Smokey’s Utilities used to also pinned ffz highlighted users. This no longer working as such. Was it previously a bug and not intentional?

**Comment by Balentay** [comment]
If it wasn't intentional I would love for it to become a main feature.  It was the only way I was keeping track of some people in a busy chat

**Comment by Mrcl1450** [comment]
+1 for this

**Comment by SirStendec** [comment]
Ended up implementing this myself, since Smokey's been busy with other stuff.

Fixed in 4ea0962e3be47d15b7606b611e4481c1a25c51af
