### ISSUE TITLE
"When in portrait mode, place chat at the top." Stopped working properly.

### ISSUE THREAD

**Issue by cyrogoncalves** [FrankerFaceZ/Add-Ons#67]
On portrait mode when you enable Appearance » Layout » "When in portrait mode, place chat at the top." the chat goes up, but the video doesn't go below it anymore. The chat is probably covering the stream now.

It started happening today for me. I tested both on Chrome and on Firefox and got the same problem. In Firefox I had a fresh installation, so I don't think it's something particular to my settings.

**Comment by Lordmau5** [comment]
I know it's been roughly 2 years but I've checked just now and it seems to be working correctly so I'm gonna close this.
