### ISSUE TITLE
[Inline Tab] Unintuitive order of suggested emotes

### ISSUE THREAD

**Issue by Munzu** [FrankerFaceZ/Add-Ons#68]
I personally find the current order of suggested emotes a little unintuitive.

For example, when I type `wa` and press Tab, I expect it to auto-complete it to something like `WAYTOODANK` because it starts with `wa`. Instead, it auto-completes to `BCWarrior` and a whole bunch of other emotes first, even though they don't start with `wa`. I'm guessing this is because their first letters come earlier in the alphabet.

Also, when I type `om` and press Tab, I expect it to auto-complete to `OMEGALUL`. Instead, it auto-completes to `OMEGALULiguess` first. 

Is there any chance FFZ could prioritize matches at the start of the string, as well as shorter strings instead of longer ones?
Thanks in advance for any reply.

**Comment by Munzu** [comment]
It seems the prioritization of `OMEGALUL` and `OMEGALULiguess` is inconsistent. Sometimes, `OMEGALULiguess` comes up first, other times `OMEGALUL` comes up first.

**Comment by Railander** [comment]
Unfortunately still waiting for a fix.

The workaround I found is manually adding the emotes that should go first to my favorites. You can do so by opening the emotes list and CTRL+clicking it.

**Comment by doubledgedboard** [comment]
This isn't fixed and should be reopened.
