### ISSUE TITLE
[smokemotes] Channel point auto-claimer duplicate setting

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/Add-Ons#74]
@smokey019's Utilities contains an `Auto Point Claimer` setting that is largely obsolete now that it is implemented in FFZ Core with a visible setting. Might be worth to clean up the add-on setting, perhaps migrating from the add-on as it is disabled by default.

Thanks,
Elliott

**Comment by smokey019** [comment]
one day i'll update it

**Comment by pointydev** [comment]
Closed by b68230b.
