### ISSUE TITLE
Fix Compatibility with Pale Moon 29.2.1 

### ISSUE THREAD

**Issue by billy2k19** [FrankerFaceZ/Add-Ons#78]
Pale Moon 29.2.1 broke compatibility with many previous Add-ons (including FrankerFaceZ)

see:

https://forum.palemoon.org/viewtopic.php?f=1&t=26657

**Comment by SirStendec** [comment]
Pale Moon is not officially supported by FrankerFaceZ. As a rule, I don't go out of my way to support browsers that are just forks of other popular browsers but with their own separate add-on repository.

Please just use the userscript version of FrankerFaceZ with whichever Pale Moon add-on(s) facilitate userscripts. The userscript version of FrankerFaceZ is functionally equivalent to the loader extensions for Chrome and Firefox.
