### ISSUE TITLE
[FS Chat] Metadata Shifted to the left from the main chat in VODs (Bug)

### ISSUE THREAD

**Issue by tballas** [FrankerFaceZ/Add-Ons#83]
The metadata below chat in FS Chat in VODs only is shifted to the left from the main chat playback.

![FS Chat on vods error](https://user-images.githubusercontent.com/5836276/132571068-a62be4fb-cd88-4eed-9c4c-19296cb86d07.png)

**Comment by SirStendec** [comment]
Closed by 22e6d6ea354221274aa6ba1098a52e81e7d3ca78
