### ISSUE TITLE
[Deck] - Feature Request - Recommended smaller communities

### ISSUE THREAD

**Issue by CreeperChief** [FrankerFaceZ/Add-Ons#87]
Right now you can add a column of Recommended channels.

Can you also add an option to add a column for Recommended smaller communities?

Thank you in advance.

**Comment by SirStendec** [comment]
No. There is no endpoint for recommended smaller communities that I am aware of.

The front page of Twitch uses a system called "shelves", where the client has very little control over what data is returned. It isn't something that would work well with Deck.
